//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class AktBenutzer
    {
        public string Akb_Dbuser { get; set; }
        public string Akb_Session { get; set; }
        public int Akb_BenutzerID { get; set; }
        public Nullable<int> Akb_Schule { get; set; }
        public Nullable<int> Akb_Abteilung { get; set; }
        public string Akb_Benutzeraccount { get; set; }
        public string Akb_Usernewupd { get; set; }
        public string Akb_Benutzernachname { get; set; }
        public string Akb_Benutzervorname { get; set; }
        public string Akb_Benutzername { get; set; }
        public string Akb_Benutzernamevz { get; set; }
        public string Akb_Benutzernametitel { get; set; }
        public string Akb_Benutzernametitelvz { get; set; }
        public string Akb_User_neu { get; set; }
        public Nullable<System.DateTime> Akb_Date_neu { get; set; }
        public string Akb_User_upd { get; set; }
        public Nullable<System.DateTime> Akb_Date_upd { get; set; }
    
        public virtual Infobenutzer Infobenutzer { get; set; }
    }
}
