//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplBen
    {
        public int Dib_Diplomprojekt { get; set; }
        public int Dib_Benutzer { get; set; }
        public bool Dib_Isthauptverantwortlich { get; set; }
        public Nullable<System.DateTime> Dib_Datetime_new { get; set; }
        public Nullable<int> Dib_Stundenanzahl { get; set; }
    
        public virtual Infobenutzer Infobenutzer { get; set; }
    }
}
