//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diplomprojekte
    {
        public int Di_ID { get; set; }
        public int Di_Abteilung { get; set; }
        public string Di_Ausbildungsschwerpunkt { get; set; }
        public string Di_Titel { get; set; }
        public string Di_Untertitel { get; set; }
        public string Di_Aufgabenstellung { get; set; }
        public string Di_Zielsetzung { get; set; }
        public string Di_geplantes_Ergebnis { get; set; }
        public string Di_Meilenstein { get; set; }
        public string Di_Rechtliche_Regelung { get; set; }
        public string Di_Praesentationsname { get; set; }
        public string Di_Titel_Englisch { get; set; }
        public string Di_Zusammenfassung { get; set; }
        public string Di_Zusammenfassung_Englisch { get; set; }
        public string Di_Typ { get; set; }
        public string Di_Stichwoerter { get; set; }
        public string Di_Stichwoerter_Englisch { get; set; }
        public string Di_Link_Projektseite { get; set; }
        public string Di_Umfeld { get; set; }
        public Nullable<bool> Di_Sperrvermerk { get; set; }
        public int Di_Schule { get; set; }
        public int Dis_Ablaufschritt { get; set; }
        public System.DateTime Dis_Start { get; set; }
        public string As_Bezeichnung { get; set; }
        public string As_Beschreibung { get; set; }
        public string As_Benutzerart { get; set; }
        public string Akb_Session { get; set; }
        public int Akb_Benutzerid { get; set; }
        public string Akb_Benutzername { get; set; }
        public string akb_Benutzeraccount { get; set; }
    }
}
