//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infobenutzer
    {
        public Infobenutzer()
        {
            this.AktBenutzers = new HashSet<AktBenutzer>();
            this.DiplBens = new HashSet<DiplBen>();
        }
    
        public int Ben_ID { get; set; }
        public int Ben_Schule { get; set; }
        public string Ben_Titelvor { get; set; }
        public string Ben_Vorname { get; set; }
        public string Ben_Nachname { get; set; }
        public string Ben_Titelnach { get; set; }
        public string Ben_Email { get; set; }
        public string Ben_Klasse { get; set; }
        public string Ben_Benutzerart { get; set; }
        public string Ben_Accountname { get; set; }
        public string Ben_Passwort { get; set; }
        public Nullable<bool> Ben_Aktiv { get; set; }
        public string Bea_Nr { get; set; }
        public string Bea_Name { get; set; }
        public Nullable<int> Ben_IstinDiplomprojekten { get; set; }
        public int Ben_IstAV { get; set; }
        public int Ben_IstDirektor { get; set; }
        public int Ben_IstLsi { get; set; }
        public string Akb_Session { get; set; }
        public int Akb_Benutzerid { get; set; }
        public string Akb_Benutzername { get; set; }
        public string akb_Benutzeraccount { get; set; }
    
        public virtual ICollection<AktBenutzer> AktBenutzers { get; set; }
        public virtual ICollection<DiplBen> DiplBens { get; set; }
    }
}
