//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoAbteilungen
    {
        public int Abt_ID { get; set; }
        public string Abt_Bezeichnung { get; set; }
        public int Abt_AV { get; set; }
        public int Abt_Schule { get; set; }
        public string Ben_Nachname { get; set; }
        public string Ben_Vorname { get; set; }
        public string Ben_Name { get; set; }
        public string Ben_Namevz { get; set; }
        public string Ben_Nametitel { get; set; }
        public string Ben_Nametitelvz { get; set; }
        public string Akb_Session { get; set; }
        public int Akb_Benutzerid { get; set; }
        public string Akb_Benutzername { get; set; }
        public string akb_Benutzeraccount { get; set; }
    }
}
