//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoDiplomschritte
    {
        public int Di_ID { get; set; }
        public string Di_Titel { get; set; }
        public int Dis_Ablaufschritt { get; set; }
        public int Dis_Ben_ID { get; set; }
        public System.DateTime Dis_Start { get; set; }
        public string Dis_Kommentar { get; set; }
        public int As_Order { get; set; }
        public string As_Bezeichnung { get; set; }
        public string As_Beschreibung { get; set; }
        public string As_Benutzerart { get; set; }
        public string Akb_Session { get; set; }
        public int Akb_Benutzerid { get; set; }
        public string Akb_Benutzername { get; set; }
        public string akb_Benutzeraccount { get; set; }
    
        public virtual InfoDiplomprojekte InfoDiplomprojekte { get; set; }
    }
}
